services:
  app:
    build: .
    container_name: app_veiculos
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - neo4j
    environment:
      - DATABASE_URL=postgresql://postgres:admin123@postgres:5432/veiculos_db
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=novasenha123
      - PYTHONIOENCODING=utf-8
      - PYTHONUTF8=1
    volumes:
      - .:/app
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: postgres_clean
    environment:
      POSTGRES_DB: veiculos_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_INITDB_ARGS: "--auth-host=md5 --auth-local=md5"
    ports:
      - "5432:5432"
    volumes:
      - postgres_clean_data:/var/lib/postgresql/data
    restart: unless-stopped

  neo4j:
    image: neo4j:latest
    container_name: neo4j_clean
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/novasenha123
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    volumes:
      - neo4j_clean_data:/data
    restart: unless-stopped

volumes:
  postgres_clean_data:
  neo4j_clean_data: